language: java

before_install:
  - wget http://dl.google.com/android/android-sdk_r21.1-linux.tgz
  - tar -zxf android-sdk_r21.1-linux.tgz
  - export ANDROID_HOME=~/build/abarisain/dmix/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - android update sdk --filter 1,3 --no-ui --force

script:
  - cd ~/build/abarisain/dmix/MPDroid
  - echo "sdk.dir=/home/travis/build/abarisain/dmix/android-sdk-linux" > local.properties
  - ant clean
  - ant debug
